# Generated by Django 3.2.4 on 2021-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp1', '0003_auto_20210612_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
